/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedEmpresasIndexRouteImport } from './routes/_authenticated/empresas.index'
import { Route as AuthenticatedEmpresasCompanyIdRouteImport } from './routes/_authenticated/empresas.$companyId'
import { Route as AuthenticatedEmpresasCompanyIdIndexRouteImport } from './routes/_authenticated/empresas.$companyId.index'
import { Route as AuthenticatedEmpresasCompanyIdExportarRouteImport } from './routes/_authenticated/empresas.$companyId.exportar'
import { Route as AuthenticatedEmpresasCompanyIdImportarRouteImport } from './routes/_authenticated/empresas.$companyId.importar'
import { Route as AuthenticatedEmpresasCompanyIdPlanoDeContasRouteImport } from './routes/_authenticated/empresas.$companyId.plano-de-contas'
import { Route as AuthenticatedEmpresasCompanyIdRegrasRouteImport } from './routes/_authenticated/empresas.$companyId.regras'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEmpresasIndexRoute =
  AuthenticatedEmpresasIndexRouteImport.update({
    id: '/empresas/',
    path: '/empresas/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmpresasCompanyIdRoute =
  AuthenticatedEmpresasCompanyIdRouteImport.update({
    id: '/empresas/$companyId',
    path: '/empresas/$companyId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmpresasCompanyIdIndexRoute =
  AuthenticatedEmpresasCompanyIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEmpresasCompanyIdRoute,
  } as any)
const AuthenticatedEmpresasCompanyIdExportarRoute =
  AuthenticatedEmpresasCompanyIdExportarRouteImport.update({
    id: '/exportar',
    path: '/exportar',
    getParentRoute: () => AuthenticatedEmpresasCompanyIdRoute,
  } as any)
const AuthenticatedEmpresasCompanyIdImportarRoute =
  AuthenticatedEmpresasCompanyIdImportarRouteImport.update({
    id: '/importar',
    path: '/importar',
    getParentRoute: () => AuthenticatedEmpresasCompanyIdRoute,
  } as any)
const AuthenticatedEmpresasCompanyIdPlanoDeContasRoute =
  AuthenticatedEmpresasCompanyIdPlanoDeContasRouteImport.update({
    id: '/plano-de-contas',
    path: '/plano-de-contas',
    getParentRoute: () => AuthenticatedEmpresasCompanyIdRoute,
  } as any)
const AuthenticatedEmpresasCompanyIdRegrasRoute =
  AuthenticatedEmpresasCompanyIdRegrasRouteImport.update({
    id: '/regras',
    path: '/regras',
    getParentRoute: () => AuthenticatedEmpresasCompanyIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/empresas/$companyId': typeof AuthenticatedEmpresasCompanyIdRouteWithChildren
  '/empresas/': typeof AuthenticatedEmpresasIndexRoute
  '/empresas/$companyId/exportar': typeof AuthenticatedEmpresasCompanyIdExportarRoute
  '/empresas/$companyId/importar': typeof AuthenticatedEmpresasCompanyIdImportarRoute
  '/empresas/$companyId/plano-de-contas': typeof AuthenticatedEmpresasCompanyIdPlanoDeContasRoute
  '/empresas/$companyId/regras': typeof AuthenticatedEmpresasCompanyIdRegrasRoute
  '/empresas/$companyId/': typeof AuthenticatedEmpresasCompanyIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/empresas': typeof AuthenticatedEmpresasIndexRoute
  '/empresas/$companyId/exportar': typeof AuthenticatedEmpresasCompanyIdExportarRoute
  '/empresas/$companyId/importar': typeof AuthenticatedEmpresasCompanyIdImportarRoute
  '/empresas/$companyId/plano-de-contas': typeof AuthenticatedEmpresasCompanyIdPlanoDeContasRoute
  '/empresas/$companyId/regras': typeof AuthenticatedEmpresasCompanyIdRegrasRoute
  '/empresas/$companyId': typeof AuthenticatedEmpresasCompanyIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/empresas/$companyId': typeof AuthenticatedEmpresasCompanyIdRouteWithChildren
  '/_authenticated/empresas/': typeof AuthenticatedEmpresasIndexRoute
  '/_authenticated/empresas/$companyId/exportar': typeof AuthenticatedEmpresasCompanyIdExportarRoute
  '/_authenticated/empresas/$companyId/importar': typeof AuthenticatedEmpresasCompanyIdImportarRoute
  '/_authenticated/empresas/$companyId/plano-de-contas': typeof AuthenticatedEmpresasCompanyIdPlanoDeContasRoute
  '/_authenticated/empresas/$companyId/regras': typeof AuthenticatedEmpresasCompanyIdRegrasRoute
  '/_authenticated/empresas/$companyId/': typeof AuthenticatedEmpresasCompanyIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/empresas/$companyId'
    | '/empresas/'
    | '/empresas/$companyId/exportar'
    | '/empresas/$companyId/importar'
    | '/empresas/$companyId/plano-de-contas'
    | '/empresas/$companyId/regras'
    | '/empresas/$companyId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/empresas'
    | '/empresas/$companyId/exportar'
    | '/empresas/$companyId/importar'
    | '/empresas/$companyId/plano-de-contas'
    | '/empresas/$companyId/regras'
    | '/empresas/$companyId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/empresas/$companyId'
    | '/_authenticated/empresas/'
    | '/_authenticated/empresas/$companyId/exportar'
    | '/_authenticated/empresas/$companyId/importar'
    | '/_authenticated/empresas/$companyId/plano-de-contas'
    | '/_authenticated/empresas/$companyId/regras'
    | '/_authenticated/empresas/$companyId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/empresas/': {
      id: '/_authenticated/empresas/'
      path: '/empresas'
      fullPath: '/empresas/'
      preLoaderRoute: typeof AuthenticatedEmpresasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/empresas/$companyId': {
      id: '/_authenticated/empresas/$companyId'
      path: '/empresas/$companyId'
      fullPath: '/empresas/$companyId'
      preLoaderRoute: typeof AuthenticatedEmpresasCompanyIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/empresas/$companyId/': {
      id: '/_authenticated/empresas/$companyId/'
      path: '/'
      fullPath: '/empresas/$companyId/'
      preLoaderRoute: typeof AuthenticatedEmpresasCompanyIdIndexRouteImport
      parentRoute: typeof AuthenticatedEmpresasCompanyIdRoute
    }
    '/_authenticated/empresas/$companyId/exportar': {
      id: '/_authenticated/empresas/$companyId/exportar'
      path: '/exportar'
      fullPath: '/empresas/$companyId/exportar'
      preLoaderRoute: typeof AuthenticatedEmpresasCompanyIdExportarRouteImport
      parentRoute: typeof AuthenticatedEmpresasCompanyIdRoute
    }
    '/_authenticated/empresas/$companyId/importar': {
      id: '/_authenticated/empresas/$companyId/importar'
      path: '/importar'
      fullPath: '/empresas/$companyId/importar'
      preLoaderRoute: typeof AuthenticatedEmpresasCompanyIdImportarRouteImport
      parentRoute: typeof AuthenticatedEmpresasCompanyIdRoute
    }
    '/_authenticated/empresas/$companyId/plano-de-contas': {
      id: '/_authenticated/empresas/$companyId/plano-de-contas'
      path: '/plano-de-contas'
      fullPath: '/empresas/$companyId/plano-de-contas'
      preLoaderRoute: typeof AuthenticatedEmpresasCompanyIdPlanoDeContasRouteImport
      parentRoute: typeof AuthenticatedEmpresasCompanyIdRoute
    }
    '/_authenticated/empresas/$companyId/regras': {
      id: '/_authenticated/empresas/$companyId/regras'
      path: '/regras'
      fullPath: '/empresas/$companyId/regras'
      preLoaderRoute: typeof AuthenticatedEmpresasCompanyIdRegrasRouteImport
      parentRoute: typeof AuthenticatedEmpresasCompanyIdRoute
    }
  }
}

interface AuthenticatedEmpresasCompanyIdRouteChildren {
  AuthenticatedEmpresasCompanyIdExportarRoute: typeof AuthenticatedEmpresasCompanyIdExportarRoute
  AuthenticatedEmpresasCompanyIdImportarRoute: typeof AuthenticatedEmpresasCompanyIdImportarRoute
  AuthenticatedEmpresasCompanyIdPlanoDeContasRoute: typeof AuthenticatedEmpresasCompanyIdPlanoDeContasRoute
  AuthenticatedEmpresasCompanyIdRegrasRoute: typeof AuthenticatedEmpresasCompanyIdRegrasRoute
  AuthenticatedEmpresasCompanyIdIndexRoute: typeof AuthenticatedEmpresasCompanyIdIndexRoute
}

const AuthenticatedEmpresasCompanyIdRouteChildren: AuthenticatedEmpresasCompanyIdRouteChildren =
  {
    AuthenticatedEmpresasCompanyIdExportarRoute:
      AuthenticatedEmpresasCompanyIdExportarRoute,
    AuthenticatedEmpresasCompanyIdImportarRoute:
      AuthenticatedEmpresasCompanyIdImportarRoute,
    AuthenticatedEmpresasCompanyIdPlanoDeContasRoute:
      AuthenticatedEmpresasCompanyIdPlanoDeContasRoute,
    AuthenticatedEmpresasCompanyIdRegrasRoute:
      AuthenticatedEmpresasCompanyIdRegrasRoute,
    AuthenticatedEmpresasCompanyIdIndexRoute:
      AuthenticatedEmpresasCompanyIdIndexRoute,
  }

const AuthenticatedEmpresasCompanyIdRouteWithChildren =
  AuthenticatedEmpresasCompanyIdRoute._addFileChildren(
    AuthenticatedEmpresasCompanyIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedEmpresasCompanyIdRoute: typeof AuthenticatedEmpresasCompanyIdRouteWithChildren
  AuthenticatedEmpresasIndexRoute: typeof AuthenticatedEmpresasIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedEmpresasCompanyIdRoute:
    AuthenticatedEmpresasCompanyIdRouteWithChildren,
  AuthenticatedEmpresasIndexRoute: AuthenticatedEmpresasIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
